### PR TITLE
Clean up constant_medium::hit()

### LINKED ISSUE #22: Trying to understand hit function in Chapter 8 Volumes
This code snippest from Chapter 8 Volumes:

```C++
bool constant_medium::hit(const ray &r, float t_min, float t_max, hit_record& rec) const{
  // I don't know about this part, first we define db, it may be either true or false
  bool db = (drand48() < 0.00001);
  // then we define it false;
  db = false;
  // then why would be bother to write this : bool db = (drand48() < 0.00001);
  // why don't we just write : bool db = false; 
  ...
 
```

And if `db = false`,  then why would bother to write those `if (db)`s later, thanks.

### LINKED ISSUE #44: Trying to understand hit function in Chapter 8 Volumes
This code snippest from Chapter 8 Volumes:

```C++
bool constant_medium::hit(const ray &r, float t_min, float t_max, hit_record& rec) const{
  // I don't know about this part, first we define db, it may be either true or false
  bool db = (drand48() < 0.00001);
  // then we define it false;
  db = false;
  // then why would be bother to write this : bool db = (drand48() < 0.00001);
  // why don't we just write : bool db = false; 
  ...
 
```

And if `db = false`,  then why would bother to write those `if (db)`s later, thanks.

### PR DESCRIPTION
**Pull request by hollasch**
- Improve naming of debug control variable.
- Improve debug logic.
- Fix whack indentation.
- Slight code refactor.

Changes to both code & book.

Resolves #44

### CODE REVIEW

**Comment by hollasch** [comment]
@trevordblack — are you set up to compile/test this?

**Review by trevordblack — DISMISSED** [review]
Looks good to me

**Comment by trevordblack** [comment]
I didn't realize you wanted me to compile it.
Don't merge.

**Comment by trevordblack** [comment]
Whoops. That was embarrassing.

I built it and got the correct output for participating medium.
It's fine to merge now.

**Review by hollasch — COMMENTED** [review]
Thanks Trevor!

**Pull request merged**
